### ISSUE TITLE
[FEAT] 가방 내부 관련 API

### ISSUE THREAD

**Issue by minhyeokDev** [UMC-TRIPY/back-end-spring#41]
## Description
- 가방 내부에서 작동하는 API 를 구현합니다.

## To-do
- [x] 가방 내부에 메모 작성
- [x] 가방 내부에 준비물 추가
- [x] 가방 준비물 이름 수정
- [x] 가방 준비물 삭제
- [x] 가방 준비물 체크박스 기능
