### ISSUE TITLE
[FEAT] 여행 일정 등록, 확인 페이지 API

### ISSUE THREAD

**Issue by minhyeokDev** [UMC-TRIPY/back-end-spring#59]
## Description
- 여행 일정 등록, 확인 페이지에 대한 API를 개발 합니다.

## To-do
- 상세 작업 내용을 적어주세요
- [ ] 도시 검색 기능
- [ ] 도시 필터링 검색 기능
- [ ] 여행 일정 등록 기능
- [ ] 내 여행 목록 조회 기능
- [ ] 일정 공유 중인 친구 조회 기능
- [ ] 일정에 친구 초대 기능
- [ ] 상세 일정 추가 기능
- [ ] 상세 일정 수정 기능
- [ ] 상세 일정 삭제 기능
- [ ] 전체 일정 조회 기능
- [ ] 상세 일정 조회 기능(하나)
